#!/bin/bash
Input1="$1"
Input2="$2"
EXT2=".csv"
EXT3=".mat"
VIrg=","
APP="'"
ASN="_asn"
#python3 "python file/"DnsAddressTypeDestination.py "$Input1$form$EXT2" "$Output1$ASN$EXT2"
#python3 "python file/"DnsAddressTypeDestination.py "$Input2$form$EXT2" "$Output2$ASN$EXT2"
#/usr/local/MATLAB/R2020b/bin/matlab -batch "TtestplusSignTest($APP$Output1$ASN$EXT2$APP$VIrg $APP$Output2$ASN$EXT2$APP)"
/usr/local/MATLAB/R2020b/bin/matlab -batch "FindChangePTS($APP$Input1$EXT2$APP$VIrg $APP$Input2$EXT2$APP)"
/usr/local/MATLAB/R2020b/bin/matlab -batch "FindChangePTRegions($APP$Input1$EXT2$APP$VIrg $APP$Input2$EXT2$APP)"
